source 'https://rubygems.org'

gem 'redcarpet'
gem 'sprockets'
gem 'foreman', '>= 0.62.0'
gem 'stasis'
gem 'sass', :require => false
gem 'rouge', '>= 0.3.10'
gem 'thin'
gem 'uglifier'

group :development do
  gem 'capistrano'
end

group :production do
  gem 'therubyracer'
end
