source 'https://rubygems.org'

gem 'redcarpet'
gem 'sprockets', '>= 4.2.0'
gem 'foreman'
gem 'stasis'
gem 'sass', :require => false
gem 'rouge'
gem 'thin', '>= 1.6.0'
gem 'uglifier'

group :development do
  gem 'capistrano'
end

group :production do
  gem 'therubyracer'
end
